### ISSUE TITLE
根据部署文档一步步运行，安装Android终端报错！

### ISSUE THREAD

**Issue by mmwyl** [acgist/taoyao#1]
部署环境： Ubuntu 22.04，未修改源码！

cd /data/taoyao/taoyao-client-android/taoyao
 sh ./gradlew --no-daemon assembleRelease 
执行命令报错！

<img width="1043" alt="微信图片_20231120160212" src="https://github.com/acgist/taoyao/assets/13866168/d1ac0fef-faeb-4086-be09-6d62e4b8fbdf">

**Comment by kueyox** [comment]
我也遇到了类似的问题，请问楼主解决了吗？

**Comment by mmwyl** [comment]
附上完整截图：
<img width="958" alt="微信图片_20231120160828" src="https://github.com/acgist/taoyao/assets/13866168/03c3f6e5-77b7-46c6-ba87-e4cd47ca7ce4">

**Comment by acgist** [comment]
参考一下：https://github.com/acgist/taoyao/blob/master/.github/workflows/build.yml

有个依赖你没有下载

@mmwyl

**Comment by mmwyl** [comment]
> 参考一下：https://github.com/acgist/taoyao/blob/master/.github/workflows/build.yml
> 
> 有个依赖你没有下载
> 
> @mmwyl

好的
